python-version = "3.12.0"
replace-imports-with-any = [
    "pynvml.*",
    "hydra._internal.*",
    "hydra.core.override_parser.*",
    "datasets.*",
    "transformers.*",
    "vllm.*",
    "math_verify.*",
    "sympy.*",
    "torchdata.*",
    "nemo.*",
    "megatron.*",
    "ray.*",
]
